name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: Assigner
    attributes:
      label: Contact Details
      placeholder: email@example.com
    
  - type: input
    id: Assignee
    attributes:
      label: Contact Details
      placeholder: email@example.com
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - 1.0.2
        - 1.0.3
    validations:
      required: true
