name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: assigner
    attributes:
      label: Assigner Details
      placeholder: email@example.com
   
  - type: dropdown
    id: testerName
    attributes:
      label: Tester Name
      options:
        - Suman
        - Sayanth
    validations:
      required: true      
    
  - type: input
    id: assignee
    attributes:
      label: Assignee Details
      placeholder: email@example.com
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - 1.0.2
        - 1.0.3
    validations:
      required: true
      
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Issue criticality
      options:
        - label: sev1
        - label: sev2
        - label: sev3
        - label: sev4
        - label: relax lol!
